name: Autofill BIT checks

on:
  workflow_run:
    workflows: ["Build Browser"]
    types:
      - completed

jobs:
  check-files:
    name: Check files
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        list-files: shell
        ref: ${{ github.event.workflow_run.head_branch }}
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          monitored:
            - 'apps/browser/src/autofill/**'
            - 'apps/browser/src/background/**'
            - 'apps/browser/src/platform/services/browser-script-injector.service.ts'

    - name: Trigger test-all workflow in browser-interactions-testing
      if: steps.changed-files.outputs.monitored == 'true'
      uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
      with:
        token: ${{ secrets.CROSS_REPO_TOKEN }}
        repository: "${{ github.event.repository.owner.login }}/browser-interactions-testing"
        event-type: trigger-bit-tests
        client-payload: |-
          {
            "origin_issue": ${{ github.event.workflow_run.pull_requests[0].number }},
            "origin_branch": "${{ github.event.workflow_run.pull_requests[0].head.ref }}",
            "origin_repo": "${{ github.event.workflow_run.pull_requests[0].head.clients }}"
          }
