name: Autofill BIT checks

on:
  workflow_run:
    workflows: ["Build Browser"]
    types:
      - completed

jobs:
  check-files:
    name: Check files
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        list-files: shell
        # ref: context.payload.workflow_run.head_branch
        ref: ${{ github.event.workflow_run.head_branch }}
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          monitored:
            - 'apps/browser/src/autofill/**'
            - 'apps/browser/src/background/**'
            - 'apps/browser/src/platform/services/browser-script-injector.service.ts'

    - name: Trigger test-all workflow in browser-interactions-testing
      # if: steps.changed-files.outputs.monitored == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{ secrets.CROSS_REPO_TOKEN }}
        script: |
          for (const issue of context.payload.workflow_run.pull_requests) {
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: "browser-interactions-testing",
              workflow_id: "test-all.yml",
              ref: "main",
              inputs: {
                origin_issue: issue,
              },
            });
          }
